Ch 2 user resource signin
ee1922/checkam pull request #11
Opened 2021-06-10 14:00 UTC by ee1922

関連ISSUE
#3

2021-06-11 01:47 UTC, keikei0606sakurai requested changes
このコミットは大きいと思います。
このコミットに
- ログイン
- ログアウト
- cookieを利用したセッション管理
くらいの実装したものが含まれていると思います。
コミットを細かくしてみよう！！(コミットの戻し方や作り直す方法は以前、教えたと思うけど、調べたりしてわからなかったら聞いてね)
https://github.com/ee1922/checkam/pull/11/commits/60c59f97958c9d5c4b812fdf0dad356c459824ca

2021-06-11 02:50 UTC, ee1922 commented
@keikei0606sakurai 
レビューありがとうございます！
このコミットを区別することが難しいです。
新しいフィルをがいくつかあるのでsourcetreeの`stage selected line`は新ファイルで使えないです。
60c59f9

2021-06-11 06:03 UTC, keikei0606sakurai requested changes
少しだけ修正よろしくです！

2021-06-11 06:03 UTC, keikei0606sakurai commented on app/helpers/sessions_helper.rb
> +  def current_user
メソッド同士の間は一行空けよう

2021-06-11 06:03 UTC, keikei0606sakurai commented on db/schema.rb
>    create_table "users", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci" do |t|
前に確認し損ねたけど、COLLATE=utf8mb4_0900_ai_ciはあまり使わないです。
Greenだとutf8_unicode_ciを使用してるので、そちらに変更しよう！

2021-06-11 06:24 UTC, ee1922 commented on app/assets/javascripts/application.js
> +//= require bootstrap
はい必要です。
userがsignin状態でAccountにdropdown-menuを使うので必要です。

2021-06-11 06:25 UTC, ee1922 commented on app/assets/javascripts/application.js
> +//= require bootstrap
@keikei0606sakurai 
はい必要です。
userがsignin状態でAccountにdropdown-menuを使うので必要です。

2021-06-11 06:26 UTC, ee1922 commented on db/schema.rb
>    create_table "users", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci" do |t|
これは別のPRでやらせていただきます。

2021-06-11 06:26 UTC, ee1922 commented on db/schema.rb
>    create_table "users", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci" do |t|
@keikei0606sakurai 
これは別のPRでやらせていただきます。

2021-06-11 06:28 UTC, ee1922 commented on app/assets/javascripts/application.js
> +//= require bootstrap
<img width="781" alt="Screen Shot 2021-06-11 at 15 15 17" src="https://user-images.githubusercontent.com/59987229/121640999-9c08ed00-cac9-11eb-9ce6-fdac00130382.png">

2021-06-13 23:30 UTC, keikei0606sakurai approved these changes
OK!!

2021-06-13 23:30 UTC, keikei0606sakurai commented on config/routes.rb
> +  delete '/logout', to: 'sessions#destroy'
resourcesを使っても良いよ！！(明示的に/login /logoutにしたい場合は問題ないです)

2021-06-14 00:54 UTC, merged