User リソース： signup
ee1922/checkam pull request #9
Opened 2021-06-07 23:33 UTC by ee1922

Issue URL
issue #3 

開発概要
userサインアップ機能を開発した

- [x] userリソースを作成する
- [x] コントローラを作成する
- [x] signup viewを作成する

テスト内容
以下のそれぞれのurlに行ってデザインを確認する。
url：http://localhost:3000/users/new

- [x] urlに行ってname, email, password, confirmationを入れることでサインインができることを確認する。
- [x] name, email, password, confirmationのどちらがない時にサインアップできなく、原因がエラー文章として表示されることを確認する。
- [x] nameが５０文字以上だったらサインアップできなく、原因がエラー文章として表示されることを確認する。
- [x] emailが255文字以上だったらサインアップできなく、原因がエラー文章として表示されることを確認する。
- [x] user@foo,com user_at_foo.org, example.user@foo., foo@bar_baz.com, foo@bar+baz.comのようなパターンのemailだとサインアップできなく、原因がエラー文章として表示されることを確認する。

2021-06-09 05:29 UTC, keikei0606sakurai requested changes
修正お願いします！

2021-06-09 05:29 UTC, keikei0606sakurai commented on db/migrate/20210609020357_add_constrain_to_users.rb
> +class AddConstrainToUsers < ActiveRecord::Migration[5.1]
新たにマイグレーションファイルを生成するのではなく、db/migrate/20210607135501_create_users.rb
こっちのファイルを編集してください。

例えば、既にマイグレーションファイルがmasterにマージ済みで変更を加えたい場合は、このような形で新しいマイグレーションファイルを作成しても良いけど、ここでは、無駄にマイグレーションファイルが増えることになるので、今回はマイグレーションファイル一つで作成してください。

2021-06-09 05:29 UTC, keikei0606sakurai commented on db/migrate/20210609021531_add_presence_constraint_to_password_in_users.rb
> +class AddPresenceConstraintToPasswordInUsers < ActiveRecord::Migration[5.1]
こちらも同様に不要なファイルです(一つにまとめてください)

2021-06-09 05:29 UTC, keikei0606sakurai commented on spec/requests/users_spec.rb
> +
GETはOKなので、POST /createのテストも書いてみよう！

2021-06-09 13:31 UTC, keikei0606sakurai requested changes
https://github.com/ee1922/checkam/pull/9/commits/c77dbfdc158f7744063b0a0478ce019b045c698e
このコミットはrebaseしたかどうかではないと思います。

2021-06-09 13:31 UTC, keikei0606sakurai commented on spec/requests/users_spec.rb
> +        expect(response).to redirect_to(User.last)
あくまでここはredirectをされているかのテストをしているんじゃないかな？？

リダイレクトされることとuserが生成されることを同時にテストしているわけではないので、別テストとして書いた方が丁寧かなと思いました

2021-06-10 00:35 UTC, ee1922 commented on spec/requests/users_spec.rb
> +        expect(response).to redirect_to(User.last)
@keikei0606sakurai 
User.lastにリダイレクトされることはuserが生成した時にしかしないのでこのテストはuserが生成されること・リダイレクトすること・リクエストが成功することをしまえしていると思いますが...
参考：controllerコード
Ruby```
def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Checkam!"
      redirect_to @user
    else
      render 'new'
    end
  end
```

2021-06-10 02:33 UTC, keikei0606sakurai commented on spec/requests/users_spec.rb
> +        expect(response).to redirect_to(User.last)
@ee1922 伝えたいことはまとめてテストしないで欲しいということです。
一つのテストで3つ確認していることがおかしいと言ってます。

このテストで確認していることはなんですか？？
responseがredirectされることを期待するテストを書いてると思います。

結果的に、userが生成されていないとリダイレクトされないということだと思いますが、それはあくまで結果的であり、その目的のテストではありません。(このテストが失敗した時、リダイレクトが失敗したのか。userが生成されなかったのか、リクエストが成功しなかったのかどれかわかりません)

いつもレビューして思いますが、フレディーが正しいということを伝えるよりもこちらがなぜレビューしているのかを考えて欲しいです。

ここのテストとかを参考にしてみてください。
https://github.com/Atrae/project_green/blob/dc4072489f1a67d74a99f96eee88c6c3fcf3d962/spec/requests/client/client_block_users_request_spec.rb#L36-L66

2021-06-10 02:37 UTC, ee1922 commented on spec/requests/users_spec.rb
> +        expect(response).to redirect_to(User.last)
@keikei0606sakurai 
フィトバック、ありがとうございます！

2021-06-10 05:25 UTC, keikei0606sakurai approved these changes
ごめん！一点だけ見落としてた！
修正して次に進んでもらえればと思います〜

2021-06-10 05:25 UTC, keikei0606sakurai commented on config/routes.rb
> +  resources :users
このルーティング設定だとindex, show, new, create, edit, update, deleteの7つのルーティングが生まれてるから下記の方が今回のscopeにおいては正しいルーティングになると思います。
```ruby
resources :users, only: %i[show new create]
```

2021-06-10 05:30 UTC, merged